import React, { useState ,useEffect} from 'react';
import './Home.css';
import ShowPostcard from './ShowPostcard';
import {Link} from 'react-router-dom';

const postcard = {
  senderName: 'Jane Doe',
  senderAddress: '456 Main St, Anytown USA',
  receiverName: 'John Smith',
  receiverAddress: '123 Main St, Anytown USA',
  imageUrl: 'https://thumbs.dreamstime.com/b/sunrise-over-beach-cancun-beautiful-mexico-40065727.jpg',
  imageAltText: 'Beach scene',
  note: 'Wish you were here!',
};
const Home = () => {
  const [postcards,setpostcards]= useState([]);
  const [newPostcardUploaded, setNewPostcardUploaded] = useState(false);

  const load = async()=>{

    let response = await fetch("http://localhost:5000/api/post", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
     // body: JSON.stringify({name:formState.name,mobile:formState.mobileNumber,email:formState.email,password:formState.password,address:formState.address}),
    });
    response = await response.json()
    console.log(response)
   setpostcards(response[0]);
  };
  
  useEffect(() => {
    load();
  }, [newPostcardUploaded]);

  const handlePostcardUpload = () => {
    // Code for uploading a new postcard
    setNewPostcardUploaded(true);
  };


      return (
      <div className="home">
        <h1>Welcome to Postcard.bond!</h1>
        <p>
          Create and send physical postcards to your friends and loved ones. Choose from a selection of images generated by our machine learning model or upload your own.
        </p>
        <button onClick={handlePostcardUpload}>
        <Link to={"/postcard"}>Create a postcard</Link>
      </button>
        <div>
        { postcards !==[]
        ?postcards.map((data)=>{
           return(
            <div>
                {data.imageAltText}
        
                 {<ShowPostcard postcard={data} />}
              </div>
           )})
           :<div> ***********</div>

        

        
      }
      </div>
        <ShowPostcard postcard={postcard} />
        <Link to={"./signup"} >SignUP</Link>
      </div>
    );
  };
  
  export default Home;
  
  
  
  
  
